"use client";

import { FormEvent, useMemo, useState } from "react";

const services = [
  { code: "IPTU", title: "2ª via do IPTU", text: "Consulte débitos e emita sua guia.", href: "https://webapp1-barrinha.cidade360.cloud/" },
  { code: "NFS-e", title: "Nota Fiscal Eletrônica", text: "Acesse a emissão de notas fiscais.", href: "https://webapp1-barrinha.cidade360.cloud/" },
  { code: "ITBI", title: "ITBI Online", text: "Inicie e acompanhe sua solicitação.", href: "https://webapp1-barrinha.cidade360.cloud/" },
  { code: "CND", title: "Certidão Negativa", text: "Emita sua certidão pela internet.", href: "https://webapp1-barrinha.cidade360.cloud/" },
  { code: "EDI", title: "Vaga em creche", text: "Consulte o cadastro e a lista de espera.", href: "https://barrinha.sp.gov.br/" },
  { code: "SIC", title: "Acesso à Informação", text: "Solicite dados e acompanhe o pedido.", href: "https://webapp1-barrinha.cidade360.cloud/" },
];

const news = [
  { date: "17 AGO 2026", tag: "Processo seletivo", title: "Relação de candidatos convocados — Edital nº 001/2026", href: "https://portal.barrinha.sp.gov.br/" },
  { date: "13 AGO 2026", tag: "Processo seletivo", title: "Publicação 38-2026 — candidatos convocados", href: "https://portal.barrinha.sp.gov.br/" },
  { date: "30 JUL 2026", tag: "Trabalho", title: "Frente Popular de Trabalho — convocação", href: "https://portal.barrinha.sp.gov.br/" },
];

const faqs = [
  ["Como emitir a segunda via do IPTU?", "Acesse o Portal do Cidadão, localize o imóvel e escolha a parcela ou guia desejada. O atalho está na área de serviços desta página."],
  ["Onde encontro concursos e processos seletivos?", "As convocações mais recentes aparecem em Notícias. A relação completa fica no Portal da Transparência e nas publicações oficiais."],
  ["Como pedir uma informação pública?", "Use o serviço Acesso à Informação (e-SIC). O pedido gera protocolo e pode ser acompanhado online."],
  ["Como falar com uma secretaria?", "A área Secretarias reúne as competências de cada setor. Para atendimento geral, ligue para (16) 3943-9400, ramal 120."],
  ["Onde consulto uma vaga em creche?", "Use o atalho EDI — Vaga em creche. Ele leva ao serviço oficial de consulta disponibilizado pelo município."],
  ["Como registrar uma reclamação ou solicitação?", "A Ouvidoria é o canal oficial. Nesta demonstração, o Resolve Barrinha mostra como o processo pode ficar mais simples e rastreável."],
];

const secretariats = ["Saúde", "Educação", "Assistência Social", "Obras", "Planejamento", "Gestão de Pessoas", "Esportes", "Cultura", "Meio Ambiente", "Procuradoria Municipal"];

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [query, setQuery] = useState("");
  const [faqOpen, setFaqOpen] = useState(0);
  const [chat, setChat] = useState(false);
  const [notice, setNotice] = useState("");
  const [protocol, setProtocol] = useState("");
  const results = useMemo(() => query.trim() ? services.filter((s) => `${s.code} ${s.title} ${s.text}`.toLowerCase().includes(query.toLowerCase())) : [], [query]);

  function sendRequest(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setProtocol(`BRH-DEMO-${Math.floor(10000 + Math.random() * 89999)}`); }

  return <>
    <a className="skip" href="#conteudo">Pular para o conteúdo</a>
    <div className="demo-bar">DEMONSTRAÇÃO CONCEITUAL — NOVO PORTAL MUNICIPAL DE BARRINHA</div>
    <header className="header">
      <div className="topline wrap"><span>Prefeitura Municipal de Barrinha</span><div><a href="#acessibilidade">Acessibilidade</a><a href="#contato">Contato</a><a href="https://portal.barrinha.sp.gov.br/" target="_blank" rel="noreferrer">Portal atual</a></div></div>
      <div className="nav wrap"><a className="brand" href="#inicio" aria-label="Barrinha Digital — início"><img src="/assets/logo-prefeitura.png" alt="Prefeitura Municipal de Barrinha" /><span><b>Barrinha</b> Digital</span></a><button className="menu" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label="Abrir menu"><i></i><i></i><i></i></button><nav className={menu ? "open" : ""}><a href="#servicos">Serviços</a><a href="#noticias">Notícias</a><a href="#cidade">Cidade</a><a href="#transparencia">Transparência</a><a href="#faq">Dúvidas</a></nav><a className="outline small" href="#painel">Painel da Prefeitura</a></div>
    </header>
    <main id="conteudo">
      <section className="hero" id="inicio"><div className="hero-bg"></div><div className="wrap hero-grid"><div className="hero-copy"><span className="kicker">SERVIÇOS PÚBLICOS EM UM SÓ LUGAR</span><h1>A Prefeitura mais perto de você.</h1><p>Encontre serviços, acompanhe solicitações e saiba o que acontece em Barrinha com linguagem clara e acesso rápido.</p><div className="search-shell"><label htmlFor="busca">O que você precisa hoje?</label><div><input id="busca" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Ex.: IPTU, creche, nota fiscal" /><button onClick={() => !query && setNotice("Digite o serviço que deseja encontrar.")}>Buscar</button></div>{query && <div className="search-results">{results.length ? results.map((r) => <a key={r.code} href={r.href} target="_blank" rel="noreferrer"><b>{r.title}</b><span>{r.text}</span></a>) : <p>Nenhum atalho exato. Pergunte à BarrinhIA ou consulte todos os serviços.</p>}</div>}</div><div className="quick-links"><span>Mais procurados:</span><button onClick={() => setQuery("IPTU")}>IPTU</button><button onClick={() => setQuery("creche")}>Creche</button><button onClick={() => setQuery("Nota Fiscal")}>Nota fiscal</button></div></div><aside className="hero-card"><span className="status">ATENDIMENTO AO CIDADÃO</span><h2>Resolva sem sair de casa</h2><p>Acesse serviços oficiais ou registre uma solicitação com protocolo e acompanhamento.</p><a href="#resolve" className="button light">Abrir Resolve Barrinha</a><dl><div><dt>Telefone</dt><dd>(16) 3943-9400</dd></div><div><dt>Endereço</dt><dd>Praça Antônio Prado, 70</dd></div></dl></aside></div></section>

      <section className="services section" id="servicos"><div className="wrap"><div className="section-head"><div><span className="kicker dark">ACESSO RÁPIDO</span><h2>Serviços mais procurados</h2></div><a href="https://portal.barrinha.sp.gov.br/" target="_blank" rel="noreferrer">Ver todos os serviços</a></div><div className="service-grid">{services.map((s) => <a className="service-card" key={s.code} href={s.href} target="_blank" rel="noreferrer"><span>{s.code}</span><div><h3>{s.title}</h3><p>{s.text}</p></div><b aria-hidden="true">→</b></a>)}</div></div></section>

      <section className="section news-section" id="noticias"><div className="wrap news-grid"><div><div className="section-head"><div><span className="kicker dark">INFORMAÇÃO OFICIAL</span><h2>Últimas notícias</h2></div><a href="https://portal.barrinha.sp.gov.br/noticias/" target="_blank" rel="noreferrer">Todas as notícias</a></div><article className="featured-news"><img src="/assets/prefeitura-barrinha.jpg" alt="Prédio da Prefeitura Municipal de Barrinha" /><div><span>PROCESSO SELETIVO</span><time>17 de agosto de 2026</time><h3>Relação de candidatos convocados — Edital nº 001/2026</h3><p>Consulte a publicação oficial e as orientações aos candidatos convocados.</p><a href={news[0].href} target="_blank" rel="noreferrer">Ler publicação oficial</a></div></article><div className="news-list">{news.slice(1).map((n) => <a key={n.date} href={n.href} target="_blank" rel="noreferrer"><time>{n.date}</time><div><span>{n.tag}</span><h3>{n.title}</h3></div><b>→</b></a>)}</div></div><aside className="agenda"><span className="kicker dark">AGENDA MUNICIPAL</span><h2>Datas importantes</h2><p className="empty-label">Área preparada para eventos, campanhas, audiências públicas e prazos de inscrição.</p><div className="agenda-demo"><b>Uma publicação alimenta tudo</b><p>Ao cadastrar um evento no painel, ele aparece aqui, na secretaria responsável e na base da BarrinhIA.</p></div><button className="outline" onClick={() => setNotice("Na versão integrada, o cidadão poderá assinar alertas por assunto.")}>Quero receber avisos</button></aside></div></section>

      <section className="city-section" id="cidade"><div className="wrap"><div className="section-title light-title"><span className="kicker">UMA PLATAFORMA PARA A CIDADE</span><h2>Mais que um portal institucional.</h2><p>Serviços digitais que aproximam gestão pública, moradores e desenvolvimento local.</p></div><div className="city-grid"><article><span>01</span><h3>Resolve Barrinha</h3><p>Solicitações com foto, localização, protocolo e acompanhamento do atendimento.</p><a href="#resolve">Registrar solicitação</a></article><article><span>02</span><h3>Compre em Barrinha</h3><p>Guia de empresas, MEIs e prestadores locais com moderação da Prefeitura.</p><button onClick={() => setNotice("Cadastro de comércio: envio, validação documental e aprovação antes da publicação.")}>Conhecer a proposta</button></article><article><span>03</span><h3>Trabalhe em Barrinha</h3><p>Central de vagas locais com publicação aprovada e candidatura simplificada.</p><button onClick={() => setNotice("Empresas poderão enviar vagas para análise da equipe municipal.")}>Conhecer a proposta</button></article><article><span>04</span><h3>Barrinha em Obras</h3><p>Mapa de obras com contratos, valores, fotos, andamento e última atualização.</p><button onClick={() => setNotice("O módulo exibirá apenas dados sincronizados e validados pela Prefeitura.")}>Conhecer a proposta</button></article></div></div></section>

      <section className="section resolve" id="resolve"><div className="wrap resolve-grid"><div><span className="kicker dark">OUVIDORIA SIMPLES E RASTREÁVEL</span><h2>Mostre o problema. Acompanhe a solução.</h2><p>Uma experiência de “156 digital” para iluminação, vias, limpeza, poda, sinalização e outros serviços urbanos.</p><ol><li><b>1</b><span><strong>Informe o local</strong>Endereço ou posição no mapa</span></li><li><b>2</b><span><strong>Descreva a situação</strong>Categoria, texto e foto opcional</span></li><li><b>3</b><span><strong>Receba o protocolo</strong>Acompanhe cada mudança de status</span></li></ol></div><form className="request-form" onSubmit={sendRequest}><div className="form-head"><b>Nova solicitação</b><span>DEMONSTRAÇÃO</span></div>{protocol ? <div className="success"><span>PROTOCOLO GERADO</span><strong>{protocol}</strong><p>Na versão final, você receberia a confirmação e poderia acompanhar o andamento.</p><button type="button" onClick={() => setProtocol("")}>Criar outra solicitação</button></div> : <><label>Tipo de solicitação<select required defaultValue=""><option value="" disabled>Selecione uma categoria</option><option>Iluminação pública</option><option>Buraco ou pavimentação</option><option>Limpeza urbana</option><option>Poda de árvore</option><option>Sinalização</option><option>Outro</option></select></label><label>Endereço<input required placeholder="Rua, número e bairro" /></label><label>Descrição<textarea required placeholder="Conte o que aconteceu, sem inserir dados pessoais sensíveis"></textarea></label><label className="consent"><input type="checkbox" required /><span>Li o aviso de privacidade e autorizo o uso destes dados para atendimento da solicitação.</span></label><button className="button" type="submit">Gerar protocolo de demonstração</button></>}</form></div></section>

      <section className="transparency" id="transparencia"><div className="wrap transparency-grid"><div><span className="kicker">TRANSPARÊNCIA PARA GENTE NORMAL</span><h2>Dados públicos claros, sem esconder a fonte oficial.</h2><p>Gráficos acessíveis, explicações e filtros ajudam o cidadão a entender receitas, despesas, contratos, licitações e obras. Cada informação mantém vínculo direto com o dado de origem.</p><a className="button light" href="https://www.barrinha.sp.gov.br/transparencia/" target="_blank" rel="noreferrer">Acessar Portal da Transparência</a></div><div className="data-card"><div><span>Receitas</span><b>Fonte oficial</b></div><div><span>Despesas</span><b>Fonte oficial</b></div><div><span>Licitações</span><b>Fonte oficial</b></div><div><span>Contratos</span><b>Fonte oficial</b></div><small>Nenhum valor ilustrativo é apresentado como dado real nesta demonstração.</small></div></div></section>

      <section className="section panel-section" id="painel"><div className="wrap panel-grid"><div className="panel-visual"><div className="panel-nav"><img src="/assets/logo-prefeitura.png" alt="" /><span>Comunicação</span><span>Serviços</span><span>Obras</span><span>Ouvidoria</span><span>Permissões</span></div><div className="panel-content"><small>PAINEL DA COMUNICAÇÃO</small><h3>O que deseja publicar?</h3><div className="publish-types"><b>Notícia</b><b>Aviso</b><b>Evento</b><b>Vaga</b></div><label>Escreva como você falaria<textarea readOnly value="Amanhã vai ter vacinação no posto central das 8h às 16h. Levar documento." /></label><button>Organizar texto com IA</button></div></div><div><span className="kicker dark">FÁCIL PARA QUEM PUBLICA. SEGURO PARA QUEM GESTIONA.</span><h2>Se sabe enviar uma mensagem, sabe atualizar o portal.</h2><p>O servidor escreve, dita ou envia um documento. A IA organiza o conteúdo, mas nunca publica sozinha. A equipe revisa, aprova e mantém o histórico.</p><ul><li>Permissões por secretaria e função</li><li>Fluxo opcional de revisão e aprovação</li><li>Trilha de auditoria de cada alteração</li><li>Autenticação forte e sessões protegidas</li><li>Versionamento e restauração de conteúdo</li><li>Base oficial controlada para a BarrinhIA</li></ul></div></div></section>

      <section className="section faq" id="faq"><div className="wrap faq-grid"><div><span className="kicker dark">RESPOSTAS DIRETAS</span><h2>Dúvidas frequentes</h2><p>Conteúdo estruturado para aparecer melhor em buscadores, assistentes de voz e respostas de inteligência artificial.</p><button className="button" onClick={() => setChat(true)}>Perguntar à BarrinhIA</button></div><div className="accordion">{faqs.map((f, i) => <article className={faqOpen === i ? "active" : ""} key={f[0]}><button onClick={() => setFaqOpen(faqOpen === i ? -1 : i)} aria-expanded={faqOpen === i}><span>{f[0]}</span><b>{faqOpen === i ? "−" : "+"}</b></button><div><p>{f[1]}</p></div></article>)}</div></div></section>

      <section className="security" id="acessibilidade"><div className="wrap security-grid"><div><span>WCAG</span><b>Acessibilidade desde o projeto</b><p>Navegação por teclado, contraste, foco visível, linguagem simples e compatibilidade com leitores de tela.</p></div><div><span>LGPD</span><b>Privacidade por padrão</b><p>Coleta mínima, consentimento contextual, retenção definida e direitos do titular documentados.</p></div><div><span>OWASP</span><b>Segurança verificável</b><p>WAF, proteção contra abuso, controle de acesso, auditoria, backups e testes contínuos.</p></div></div></section>

      <section className="section secretariats"><div className="wrap"><div className="section-head"><div><span className="kicker dark">ESTRUTURA MUNICIPAL</span><h2>Secretarias e áreas de atendimento</h2></div><a href="https://portal.barrinha.sp.gov.br/secretarias/" target="_blank" rel="noreferrer">Ver responsáveis e atribuições</a></div><div className="secretariat-list">{secretariats.map((s) => <a key={s} href="https://portal.barrinha.sp.gov.br/secretarias/" target="_blank" rel="noreferrer"><span>{s}</span><b>→</b></a>)}</div></div></section>
    </main>

    <footer id="contato"><div className="wrap footer-grid"><div><img src="/assets/logo-prefeitura.png" alt="Prefeitura Municipal de Barrinha" /><p>Praça Antônio Prado, 70<br />Centro, Barrinha/SP — CEP 14860-027</p><p>(16) 3943-9400 — Ramal 120</p></div><div><b>Serviços</b><a href="#servicos">Serviços online</a><a href="#resolve">Ouvidoria</a><a href="https://www.barrinha.sp.gov.br/transparencia/">Transparência</a></div><div><b>Município</b><a href="https://portal.barrinha.sp.gov.br/sobre/">Sobre Barrinha</a><a href="https://portal.barrinha.sp.gov.br/secretarias/">Secretarias</a><a href="https://portal.barrinha.sp.gov.br/noticias/">Notícias</a></div><div><b>Acesso</b><a href="#acessibilidade">Acessibilidade</a><a href="#faq">Dúvidas frequentes</a><a href="https://www.instagram.com/prefeituradebarrinha/">Instagram oficial</a></div></div><div className="wrap footer-bottom"><span>Demonstração conceitual — conteúdo oficial vinculado às fontes da Prefeitura.</span><a href="#inicio">Voltar ao topo</a></div></footer>

    <button className="ai-fab" onClick={() => setChat(!chat)} aria-expanded={chat}><span>B</span><b>Fale com a BarrinhIA</b></button>{chat && <aside className="chat" aria-label="BarrinhIA"><div className="chat-head"><div><span>B</span><b>BarrinhIA<small>Assistente municipal — demonstração</small></b></div><button onClick={() => setChat(false)} aria-label="Fechar">×</button></div><div className="chat-body"><p className="bot">Olá. Posso ajudar a encontrar serviços e informações oficiais de Barrinha. Não informe CPF, senhas ou dados médicos.</p><button onClick={() => setNotice("Para emitir IPTU, use o atalho 2ª via do IPTU na seção Serviços.")}>Como emitir IPTU?</button><button onClick={() => setNotice("As convocações estão na área Notícias e no Portal da Transparência.")}>Onde vejo processos seletivos?</button><button onClick={() => setNotice("Use o Resolve Barrinha para registrar e acompanhar uma solicitação.")}>Quero registrar um problema</button></div><form onSubmit={(e) => { e.preventDefault(); setNotice("Nesta demonstração, a BarrinhIA responde por atalhos. Na produção, usará apenas fontes oficiais aprovadas."); }}><input aria-label="Mensagem" placeholder="Digite sua dúvida" /><button>Enviar</button></form><small>Respostas devem citar a fonte oficial. A IA não altera cadastros nem protocolos.</small></aside>}{notice && <div className="toast" role="status"><span>{notice}</span><button onClick={() => setNotice("")}>Fechar</button></div>}
  </>;
}
