"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Shell, news, services } from "./portal-ui";

export default function Home(){
 const [query,setQuery]=useState("");
 const results=useMemo(()=>query?services.filter(s=>(s.title+s.desc+s.code).toLowerCase().includes(query.toLowerCase())):[],[query]);
 return <Shell>
  <section className="hero"><div className="hero-bg"/><div className="wrap hero-grid"><div className="hero-copy"><span className="kicker">SERVIÇOS PÚBLICOS EM UM SÓ LUGAR</span><h1>A Prefeitura mais perto de você.</h1><p>Encontre serviços, acompanhe solicitações e saiba o que acontece em Barrinha com linguagem clara e acesso rápido.</p><div className="search-shell"><label htmlFor="busca">O que você precisa hoje?</label><div><input id="busca" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: IPTU, creche, nota fiscal"/><Link href={query?"/servicos?q="+encodeURIComponent(query):"/servicos"}>Buscar</Link></div>{query&&<div className="search-results">{results.slice(0,4).map(r=><a key={r.code} href={r.href}><b>{r.title}</b><span>{r.desc}</span></a>)}{!results.length&&<p>Veja todos os serviços ou pergunte à BarrinhIA.</p>}</div>}</div><div className="quick-links"><span>Mais procurados:</span><button onClick={()=>setQuery("IPTU")}>IPTU</button><button onClick={()=>setQuery("creche")}>Creche</button><button onClick={()=>setQuery("Nota Fiscal")}>Nota fiscal</button></div></div><aside className="hero-card"><span className="status">ATENDIMENTO AO CIDADÃO</span><h2>Resolva sem sair de casa</h2><p>Acesse serviços oficiais ou registre uma solicitação demonstrativa com protocolo.</p><Link href="/ouvidoria" className="button light">Abrir Resolve Barrinha</Link><dl><div><dt>Telefone</dt><dd>(16) 3943-9400</dd></div><div><dt>Endereço</dt><dd>Praça Antônio Prado, 70</dd></div></dl></aside></div></section>
  <section className="section"><div className="wrap"><div className="section-head"><div><span className="kicker dark">ACESSO RÁPIDO</span><h2>Serviços mais procurados</h2></div><Link href="/servicos">Ver todos os serviços</Link></div><div className="service-grid">{services.slice(0,6).map(s=><a className="service-card" href={s.href} key={s.code}><span>{s.code}</span><div><h3>{s.title}</h3><p>{s.desc}</p></div><b>→</b></a>)}</div></div></section>
  <section className="section news-section"><div className="wrap news-grid"><div><div className="section-head"><div><span className="kicker dark">INFORMAÇÃO OFICIAL</span><h2>Últimas notícias</h2></div><Link href="/noticias">Todas as notícias</Link></div><article className="featured-news"><img src="/assets/prefeitura-barrinha.jpg" alt="Prédio da Prefeitura Municipal de Barrinha"/><div><span>{news[0][1]}</span><time>{news[0][0]}</time><h3>{news[0][2]}</h3><p>Consulte a publicação oficial e as orientações aos candidatos convocados.</p><a href="https://portal.barrinha.sp.gov.br/">Abrir publicação oficial</a></div></article></div><aside className="agenda"><span className="kicker dark">NAVEGUE PELA CIDADE</span><h2>Tudo em um só portal</h2><Link className="city-link" href="/empregos"><b>Trabalhe em Barrinha</b><span>Vagas e oportunidades locais</span></Link><Link className="city-link" href="/comercio-local"><b>Compre em Barrinha</b><span>Empresas e prestadores locais</span></Link><Link className="city-link" href="/obras"><b>Barrinha em Obras</b><span>Acompanhe projetos municipais</span></Link></aside></div></section>
  <section className="home-cta"><div className="wrap"><div><span className="kicker">PARTICIPE DA CIDADE</span><h2>Viu algo que precisa de atenção?</h2><p>Registre iluminação, limpeza, pavimentação, poda e outros serviços urbanos.</p></div><Link className="button light" href="/ouvidoria">Abrir solicitação</Link></div></section>
 </Shell>
}
